# Generated by Django 3.2.4 on 2021-06-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('main_category', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='home.category')),
                ('sub_category', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='home.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Window',
        ),
    ]
