# Generated by Django 3.2.4 on 2021-06-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210619_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='count',
            new_name='relation_count',
        ),
    ]
