# Generated by Django 3.2.4 on 2021-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_count_topic_relation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='contetn',
            field=models.TextField(default='textfield'),
            preserve_default=False,
        ),
    ]
