# Generated by Django 3.1.3 on 2021-06-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210620_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='home.category'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='home.subcategory'),
        ),
    ]
