# Generated by Django 3.1.3 on 2021-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210620_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='svg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
